社員登録アプリ
maichang/employee_list pull request #1
Opened 2020-01-20 06:01 UTC by maichang

## 仕様
メニュー
- 登録
- 一覧
- 削除
- 終了

## バリデーション
名前
- 空白の入力

誕生日
- 空白の入力
- 正規表現（OK例： `1999-07-21`）
- 不正の日付（存在しない日付）
- 15歳未満の登録はできない

給与
- 空白の入力
- マイナスの数値

2020-01-20 06:55 UTC, myohei requested changes
やってみてください〜

2020-01-20 06:55 UTC, myohei commented on src/index.js
> +    salary = toInt.toLocaleString() // カンマ区切りで表示
`salary`はint型(number)で持ちましょう。
表示するときだけ、3点区切りにしましょう

2020-01-20 06:55 UTC, myohei commented on src/index.js
> +    const toInt = (typeof inputSalary !== 'number') ? parseInt(inputSalary, 10) : inputSalary // 数値に変換
`あああ` とか入力されたらどうなります？

2020-01-20 06:55 UTC, myohei commented on src/index.js
> +  }
1この関数にしてみましょう！
できれば`private`関数で

2020-01-20 06:55 UTC, myohei commented on src/index.js
> +  }
1この関数にしてみましょう！
できればprivate関数で

2020-01-20 06:55 UTC, myohei commented on src/index.js
> +  let salary = ''
他と同じ、
1この関数にしてみましょう！
できればprivate関数で

2020-01-20 06:56 UTC, myohei commented
他の人が実行するには、`package.json`も必要だと思う。
cloneして実行するまでの流れもREADMEに書いてみて！

2020-01-20 07:37 UTC, maichang commented on src/index.js
> +    const toInt = (typeof inputSalary !== 'number') ? parseInt(inputSalary, 10) : inputSalary // 数値に変換
@myohei 
こうなります🤔💭
```
給与 ＞あああ
＊入力必須です。
```

2020-01-20 07:41 UTC, myohei commented on src/index.js
> +    const toInt = (typeof inputSalary !== 'number') ? parseInt(inputSalary, 10) : inputSalary // 数値に変換
「数字で入力してください」ってしたいよね

2020-01-20 07:48 UTC, maichang commented on src/index.js
> +    const toInt = (typeof inputSalary !== 'number') ? parseInt(inputSalary, 10) : inputSalary // 数値に変換
直します！

2020-01-20 11:41 UTC, myohei requested changes
もう少し細かくみてみた

2020-01-20 11:41 UTC, myohei commented on package.json
> +{
どんなオプションあるか、軽くながめたり、他のリポジトリみてみたりしてね

2020-01-20 11:41 UTC, myohei commented on .babelrc
> +    "presets": ["@babel/preset-env"]
これもどんな意味あるか調べてみて

2020-01-20 11:41 UTC, myohei commented on src/employeeManager.js
> +    console.log('id name birthday saraly')
`\t` とか使うと タブになるから表示少しきれいになるかも

2020-01-20 11:41 UTC, myohei commented on src/index.js
> +const REGISTER_NUMBER = ['1', '2', '3', '4']
配列にしないで、
const REGISTER = ’1’
って個別に宣言しましょう。

2020-01-20 11:41 UTC, myohei commented on src/index.js
> +  menus.forEach(menu => console.log(menu))
わかってると思うけど、改行は\nね

2020-01-20 11:41 UTC, myohei commented on src/registerManager.js
> +      const regex = /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/
これも定数化できるかな

2020-01-20 11:41 UTC, myohei commented on src/registerManager.js
> +      const match = inputBirthday.match(regex)
requireチェックしたあとにやりましょう

2020-01-20 11:41 UTC, myohei commented on src/registerManager.js
> +      const valid = moment(inputBirthday).isValid()
requireと正規表現チェック後にやりましょう

2020-01-20 11:41 UTC, myohei commented on src/registerManager.js
> +      const age = moment().diff(inputBirthday, 'years')
requireと正規表現チェックと正しい日付のあとにやりましょう

2020-01-20 11:41 UTC, myohei commented on src/registerManager.js
> +      birthday = formatCheck
birthdayはmoment型で持たせましょう。
表示のときにformatする

2020-01-21 05:33 UTC, maichang commented on src/index.js
> +  menus.forEach(menu => console.log(menu))
今の状態で改行しなくても綺麗に表示されてるのでそのままにします！
使うとしたら `\n` 使うようにしますね✊

2020-01-21 06:18 UTC, maichang commented on src/index.js
> +const REGISTER_NUMBER = ['1', '2', '3', '4']
この場合、`REGISTER_1` `REGISTER_2` とかにするのがいいんでしょうか？💭

2020-01-21 06:48 UTC, myohei commented on src/index.js
> +const REGISTER_NUMBER = ['1', '2', '3', '4']
`1`は何を表すか、`2`は何を表すかですな。
今回だと、1は登録、2は一覧、3は…
って考えるので、

`const REGISTER_MENU = '1'`
`const SHOW_MENU = '2'`

みたいなかな

2020-01-21 06:57 UTC, maichang commented on src/index.js
> +const REGISTER_NUMBER = ['1', '2', '3', '4']
なるほどぅ！

2020-01-21 07:10 UTC, myohei approved these changes

2020-01-21 07:10 UTC, myohei commented on src/registerManager.js
> +const REGEX = /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/
ちゃんと名前つけましょう。なんの正規表現なのか

2020-01-21 07:10 UTC, myohei commented on src/registerManager.js
> +      const toMomentType = moment(inputBirthday)
何回も`moment()`やってるから変数作りましょう

2020-01-21 07:10 UTC, myohei commented on src/registerManager.js
> +        console.log('sss')
`sss`

2020-01-21 07:45 UTC, merged